-- MySQL Script generated by MySQL Workbench
-- Sun Jul 17 12:58:50 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema demo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `demo` ;

-- -----------------------------------------------------
-- Schema demo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demo` DEFAULT CHARACTER SET utf8mb4 ;
USE `demo` ;

-- -----------------------------------------------------
-- Table `demo`.`emotion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`emotion` ;

CREATE TABLE IF NOT EXISTS `demo`.`emotion` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `happy` INT NOT NULL,
  `sad` INT NOT NULL,
  `angry` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demo`.`citizen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`citizen` ;

CREATE TABLE IF NOT EXISTS `demo`.`citizen` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `emotion_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_citizen_emotion_idx` (`emotion_id` ASC),
  CONSTRAINT `fk_citizen_emotion`
    FOREIGN KEY (`emotion_id`)
    REFERENCES `demo`.`emotion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `demo`.`emotion`
-- -----------------------------------------------------
START TRANSACTION;
USE `demo`;
INSERT INTO `demo`.`emotion` (`id`, `happy`, `sad`, `angry`, `created_at`, `updated_at`, `version`) VALUES (1, 10, 0, 0, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `demo`.`emotion` (`id`, `happy`, `sad`, `angry`, `created_at`, `updated_at`, `version`) VALUES (2, 5, 5, 0, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `demo`.`emotion` (`id`, `happy`, `sad`, `angry`, `created_at`, `updated_at`, `version`) VALUES (3, 0, 5, 5, DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `demo`.`citizen`
-- -----------------------------------------------------
START TRANSACTION;
USE `demo`;
INSERT INTO `demo`.`citizen` (`id`, `emotion_id`, `name`, `created_at`, `updated_at`, `version`) VALUES (1, 1, 'Jason Park', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `demo`.`citizen` (`id`, `emotion_id`, `name`, `created_at`, `updated_at`, `version`) VALUES (2, 2, 'James Len', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `demo`.`citizen` (`id`, `emotion_id`, `name`, `created_at`, `updated_at`, `version`) VALUES (3, 3, 'Tony Stark', DEFAULT, DEFAULT, DEFAULT);

COMMIT;

